### ISSUE TITLE
add plane_shape function

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/rplanes#101]
we have done some preliminary work to establish a "shape" plausibility component. in short, this component splits a time series of seed values (i.e., observations that we trust) into a series of sliding windows. then we perform a distance calculation for all the windows and the evaluated signal. after comparing this distance for all windows *and* the evaluated signal, we determine whether or not the evaluated signal is more different than any of the "shapes" observed in the seed. if so, we raise a flag.

@abenefield1 please start implementing `plane_shape()` into the package. create a branch from this issue and when ready, open a PR to the `dev` branch. 

a few other things to consider:

- can/should we pull the "seed" process to establish the threshold for distance comparison?
- will this work on observed signals and forecasts? or just forecasts?
- do we need to require a certain amount of seed data to use this component (e.g., the [requirement in `plane_trend()` for 4x the horizon](https://github.com/signaturescience/rplanes/blob/main/R/planes.R#L636-L639))?

**Comment by abenefield1** [comment]
@vpnagraj ,

- Didn't we decide against storing the threshold in the seed for some reason? I think I remember discussing on Friday, but I can't remember the thought process.
- This should work on both observed and forecast, but we'll need to think about how to implement it. For example, you could compare the observed signal for weeks 10-14 to weeks 1-9, but you wouldn't want to somehow compare 10-14 to weeks 1-9 and 15-25. So as long as there is enough seed data _**before**_ the observed signal in question, it should work the same.
- There should be some amount of seed data required to use this component, but deciding what that should be is tricky. DTW is weird in that there aren't really any measures of confidence. I would think that one, bare minimum requisite would be that the seed data needs to have more variation than the signal data. But that's absolute bare minimum. I'm struggling to think of an objective way to arrive at a minimum seed length. We'll probably need to discuss this in more detail on a call, but it's not super urgent.

**Comment by vpnagraj** [comment]
@abenefield1 thanks for responding above ... my thoughts on those topics (in the same order):

- you're right ... we talked about it the issue of needing the horizon (number of points) in evaluated signal to create the threhsold. we don't track that anywhere in `plane_seed()` ... so yeah let's hold off on putting the threshold calculation in the seed for now. we can always revisit later.
- makes sense on observed evaluations. to start, let's just write this to work with forecasts. like the other point, we can revisit later.
- i think the 4x horizon requirement is fair to start. that much seed data should express more variation than the signal data to be evaluated, although i guess we can't know that. as with *both points above let's revisit after we get a working version of the function in the package.

**Comment by abenefield1** [comment]
I'm mostly done documenting plane_shape. There's a weird error I'm getting:
`❯ checking for unstated dependencies in examples ... ERROR
  Warning: parse error in file 'lines':
  1: unexpected symbol
  246: 
  247: prepped_seed
       ^`

Will figure out tomorrow. 

Still need to write tests and update vignette accordingly.

@vpnagraj , if you want to start taking a look at the documentation tomorrow, let me know, and I'll confirm whether or not I was able to resolve that error ^

**Comment by vpnagraj** [comment]
fixed: https://github.com/signaturescience/rplanes/commit/b9274256bc31718b8849270208197efea70a1dc4

one of the roxygen comment tags was "broken" (i.e., `#` instead of `#'`)

i pushed up the change, so make sure to pull from that branch before you keep working

also sounds like you're still going on the tests / vignette edits. i'll hold on my review of the whole thing unitl you're done with that and have submitted the PR to dev

**Comment by vpnagraj** [comment]
this was included in dev branch via https://github.com/signaturescience/rplanes/commit/24ddc402126f9bfb8c1018d258401a2e40765c5c
