### ISSUE TITLE
Add error message when forecast location doesn't exist

### ISSUE THREAD

**Issue by abenefield1** [signaturescience/rplanes#113]
We have an error message for when a location doesn't exist in the seed, but we should also include one for when a location doesn't exist in a forecast. It's unlikely that this will be a user-facing issue, but it can save us some time in dev. For example, I was writing the plane_shape test using location "01" from our TSENS forecast. This location exists in the seed, but we had censored that location from our forecast, so it didn't exist in the input. The only error message was telling me that the valid dates were null - which sent me on a wild goose chase trying to track down the issue.

`  if(!location %in% names(seed)) {
    stop(sprintf("%s does not appear in the seed object. Check that the seed was prepared with the location specified.", location))
  }`

![image](https://github.com/signaturescience/rplanes/assets/42815856/b86e70eb-eeb7-401d-8436-8751231a1921)

**Comment by vpnagraj** [comment]
@abenefield1 can you tag in to help with this?

let's abstract a the error handling for location validation to a helper that lives in utils.R. will be similar to `valid_dates()` ... let's call it `valid_locations()`. we already have the guts of this written for location check in seed:

https://github.com/signaturescience/rplanes/blob/main/R/planes.R#L42-L45

let's pull that out of the individual plane_ component function calls and put it in the helper. and add a second step to also check that the location exists in the evaluated signal.

so if im thinking about this right, i expect we would have thee arguments to `valid_locations()`: location, input, seed.

im seeing this as an unexported helper, so document accordingly.

when we have the helper written we also will need to make sure to re-implement the logic in *all of the plane_ functions

and lastly, let's write a test. here's an example of how we check error handling with `expect_error()` from testthat for `valid_dates()`:

https://github.com/signaturescience/rplanes/blob/main/tests/testthat/test-date-math.R#L13-L20

**Comment by vpnagraj** [comment]
updated via https://github.com/signaturescience/rplanes/commit/72a42d6e02c9a3891dc0166831ac54f4db17ae63

reprex below demonstrates new behavior

``` r
library(rplanes)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

## set a seed since we are sampling random values below
set.seed(321)
## create mock surveillance data
## this will include three locations
surv_data <-
  tibble(
    location = c(rep("US", 20), rep("01", 20), rep("02", 20)),
    ## randomly sample values
    cases = c(sample(200:225, size = 20), sample(200:225, size = 20), sample(200:225, size = 20)),
    date =  c(as.Date("2023-01-01") + (7*(1:20)),as.Date("2023-01-01") + (7*(1:20)), as.Date("2023-01-01") + (7*(1:20)))
  )

surv_data
#> # A tibble: 60 × 3
#>    location cases date      
#>    <chr>    <int> <date>    
#>  1 US         221 2023-01-08
#>  2 US         217 2023-01-15
#>  3 US         212 2023-01-22
#>  4 US         215 2023-01-29
#>  5 US         216 2023-02-05
#>  6 US         203 2023-02-12
#>  7 US         214 2023-02-19
#>  8 US         210 2023-02-26
#>  9 US         224 2023-03-05
#> 10 US         219 2023-03-12
#> # ℹ 50 more rows
#> # A tibble: 60 × 3
#>    location cases date      
#>    <chr>    <int> <date>    
#>  1 US         221 2023-01-08
#>  2 US         217 2023-01-15
#>  3 US         212 2023-01-22
#>  4 US         215 2023-01-29
#>  5 US         216 2023-02-05
#>  6 US         203 2023-02-12
#>  7 US         214 2023-02-19
#>  8 US         210 2023-02-26
#>  9 US         224 2023-03-05
#> 10 US         219 2023-03-12
#> # ℹ 50 more rows

## convert mock surveillance data to an observed signal
observed_signal <- to_signal(input = surv_data, outcome = "cases", type = "observed", resolution = "weeks", horizon = NULL)

## create the seed
prepped_seed <- plane_seed(observed_signal)

## create point estimates
point_est <- c(230,233,236,239,231,234,237,240)
prepped_forecast <-
  tibble(
    location = c(rep("US",4), rep("02",4)),
    date = rep(max(surv_data$date) + (7*(1:4)),2),
    horizon = rep(1:4,2),
    ## make the lower and upper bounds get wider as horizon increases
    ## NOTE: location 2 intentionally has a wider PI
    lower = point_est - c(5,10,15,20,20,30,40,50),
    point = point_est,
    upper = point_est + c(5,10,15,20,20,30,40,50)
  ) %>%
  to_signal(outcome = "cases", type = "forecast", horizon = 4)

## lets try to run the diff component on the two locations in the forecast
plane_diff("US", prepped_forecast, prepped_seed)
#> $indicator
#> [1] TRUE
#> 
#> $values
#> [1] 207 230 233 236 239
#> 
#> $evaluated_differences
#> [1] 23  3  3  3
#> 
#> $maximum_difference
#> [1] 17
#> $indicator
#> [1] TRUE
#> 
#> $values
#> [1] 207 230 233 236 239
#> 
#> $evaluated_differences
#> [1] 23  3  3  3
#> 
#> $maximum_difference
#> [1] 17
plane_diff("02", prepped_forecast, prepped_seed)
#> $indicator
#> [1] FALSE
#> 
#> $values
#> [1] 207 231 234 237 240
#> 
#> $evaluated_differences
#> [1] 24  3  3  3
#> 
#> $maximum_difference
#> [1] 24
#> $indicator
#> [1] FALSE
#> 
#> $values
#> [1] 207 231 234 237 240
#> 
#> $evaluated_differences
#> [1] 24  3  3  3
#> 
#> $maximum_difference
#> [1] 24

## now the same thing with a location in seed but not forecast
plane_diff("01", prepped_forecast, prepped_seed)
#> Error in valid_location(location, input, seed): 01 does not appear in the input object. Check that the input was prepared with the location specified.
```

<sup>Created on 2023-12-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
