### ISSUE TITLE
don't set seed inside functions

### ISSUE THREAD

**Issue by jcken95** [signaturescience/rplanes#149]
consider using [{withr}](https://withr.r-lib.org/) instead. In particular see [`withr::with_seed()`](https://withr.r-lib.org/reference/with_seed.html)

this allows you to run code _without_ modifying the global environment. In particular stops you "overwriting" or resetting the seed that a user may have set earlier in their code

https://github.com/signaturescience/rplanes/blob/6e9fe6d51647680c92624d95d0d7922175bff113/R/planes.R#L685

**Comment by vpnagraj** [comment]
thanks again for raising this issue and providing the fix via #150 

merged onto dev branch and will be part of the next release!
