### ISSUE TITLE
Edits to basic usage vignette

### ISSUE THREAD

**Issue by abenefield1** [signaturescience/rplanes#95]
In the "Analyzing plausibility of observed data/Run plane_score() and visualize results" part, I think that we should explicitly state that only diff and repeat are used on observed data. It's implied by the last sentence before the code and then the plane_score code, but I think we should be very loud about that

Under "Analyzing plausibility of forecast data," the sentence has two "to's":

"Several packages must be loaded **to** prior to conducting the analysis:"

**Comment by abenefield1** [comment]
Writing this ^ in the negative, so that we don't have to edit unless we add components that also don't work on observed signals.

**Comment by abenefield1** [comment]
Fixed and initiated PR to dev

**Comment by vpnagraj** [comment]
done and over in dev ... will be in main on our next release

https://github.com/signaturescience/rplanes/pull/100
