### ISSUE TITLE
ensure that repeats argument is documented consistently

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/rplanes#98]
in https://github.com/signaturescience/rplanes/issues/91 we updated the name mapping for `plane_repeat()` in the `plane_score()` components vector from "repeats" to "repeat" for consistency.

there is at least one place where we missed updating the usage:

https://github.com/signaturescience/rplanes/blob/main/R/planes.R#L424

need to confirm that all the documentation / tests / examples are consistent.

**Comment by abenefield1** [comment]
Note to self to check basic usage vignette too

**Comment by vpnagraj** [comment]
done and over in dev ... will be on main in our next release

https://github.com/signaturescience/rplanes/pull/99
